version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./storage/qdrant_data:/qdrant/storage  

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./storage/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  yara:
    image: xwukong/yara-agent:v0.3.0
    env_file:
      - .env
    ports:
      - 7622:7600
    depends_on:
      - postgres
      - qdrant

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@perfect3sixty.com
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8090:8080"
    volumes:
      - ./pgadmin.json:/pgadmin4/servers.json
    depends_on:
      - postgres